# format: app_name source_subpath destination_path reload_command(optional)

waybar waybar/colors.css $HOME/.config/waybar/colors.css "pkill -USR2 waybar"
hypr hypr/colors.conf $HOME/.config/hypr/colors.conf "hyprctl reload"
kitty kitty/colors.conf $HOME/.config/kitty/colors.conf ""
rofi rofi/colors.rasi $HOME/.config/rofi/colors/theme.rasi ""
