# =========================
# Background Layers
# =========================

$bg0 = 1F2D1Fff
$bg1 = 2A3D2Aff
$bg2 = 344E34ff
$bg3 = 3E5E3Eff

# =========================
# Foreground
# =========================

$fg0 = 31CB00ff 
$fg1 = 119822ff
$fg2 = 2A7221ff
$fg3 = 1E441Eff

# =========================
# Accent Colors
# =========================

$accent0 = 88C070ff
$accent1 = 70A868ff
$accent2 = 507850ff
$accent3 = C0A870ff
$accent4 = D08858ff
$accent5 = E8C840ff
$accent6 = C06070ff
$accent7 = 70C088ff

# =========================
# Status
# =========================

$status_warning = E8C840ff
$status_critical = C06070ff
$status_success = 70C088ff
