background             #2e1f22
foreground             #f9eeea
selection_background   #453133
selection_foreground   #f9eeea
cursor                 #f9eeea

color0  #2e1f22
color1  #6e1a2f
color2  #f4a7b9
color3  #f7cdd6
color4  #e8799f
color5  #c94b8a
color6  #f4a7b9
color7  #c9b0ab
color8  #523c3e
color9  #6e1a2f
color10 #f4a7b9
color11 #f7cdd6
color12 #e8799f
color13 #c94b8a
color14 #f4a7b9
color15 #f9eeea
