$bg0 = rgba(272932aa)
$bg1 = rgba(2f313caa)
$bg2 = rgba(383b47aa)
$bg3 = rgba(444857aa)
$fg0 = rgba(f2f2f2aa)
$fg1 = rgba(D1C5C0aa)
$fg2 = rgba(b0a6a2aa)
$fg3 = rgba(8a8180aa)
$accent0 = rgba(37EBF3aa)
$accent1 = rgba(1AC5B0aa)
$accent2 = rgba(9370DBaa)
$accent3 = rgba(CB1DCDaa)
$accent4 = rgba(E455AEaa)
$accent5 = rgba(FDF500aa)
$accent6 = rgba(710000aa)
$accent7 = rgba(37EBF3aa)
$status_warning = rgba(FDF500aa)
$status_critical = rgba(710000aa)
$status_success = rgba(1AC5B0aa)
