# =========================
# Background Layers
# =========================
$bg0 = rgba(2E3440ff)
$bg1 = rgba(3B4252ff)
$bg2 = rgba(434C5Eff)
$bg3 = rgba(4C566Aff)
# =========================
# Foreground
# =========================
$fg0 = rgba(ECEFF4ff)
$fg1 = rgba(E5E9F0ff)
$fg2 = rgba(D8DEE9ff)
$fg3 = rgba(8FBCBBff)
# =========================
# Accent Colors
# =========================
$accent0 = rgba(88C0D0ff)
$accent1 = rgba(81A1C1ff)
$accent2 = rgba(5E81ACff)
$accent3 = rgba(B48EADff)
$accent4 = rgba(D08770ff)
$accent5 = rgba(EBCB8Bff)
$accent6 = rgba(BF616Aff)
$accent7 = rgba(A3BE8Cff)
# =========================
# Status
# =========================
$status_warning = rgba(EBCB8Bff)
$status_critical = rgba(BF616Aff)
$status_success = rgba(A3BE8Cff)
