# Background / Foreground
background #272932
foreground #f2f2f2
selection_background #710000
selection_foreground #f2f2f2

# Cursor
cursor #37EBF3
cursor_text_color #710000

# Basic terminal colors
color0  #272932
color1  #FDF500
color2  #1AC5B0
color3  #710000
color4  #37EBF3
color5  #CB1DCD
color6  #9370DB
color7  #D1C5C0

# Bright colors
color8  #444857
color9  #E455AE
color10 #1AC5B0
color11 #FDF500
color12 #37EBF3
color13 #CB1DCD
color14 #9370DB
color15 #f2f2f2
