$bg0 = rgba(020403aa)
$bg1 = rgba(06110Aaa)
$bg2 = rgba(0B1A11aa)
$bg3 = rgba(10261Aaa)

$fg0 = rgba(E8FFE8aa)
$fg1 = rgba(B7F5B7aa)
$fg2 = rgba(7CFF7Caa)
$fg3 = rgba(4CFF4Caa)

$accent0 = rgba(00FF41aa)
$accent1 = rgba(00CC33aa)
$accent2 = rgba(00FF9Caa)
$accent3 = rgba(FF0033aa)
$accent4 = rgba(33FF88aa)
$accent5 = rgba(66FF66aa)
$accent6 = rgba(22FF22aa)
$accent7 = rgba(00FFCCaa)

$status_warning = rgba(FFD000aa)
$status_critical = rgba(FF0033aa)
$status_success = rgba(22FF22aa)

